node-formidable/formidable

lib/multipart_parser.js
Saw this popping up a bit using node v0.11.14:
`.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.`
Tested with node v0.10.33 and v0.11.14, using npm test.
=> fix deprecated Buffer.write call for node 0.11.x

lib/incoming_form.js
As the RFC 2616 section `19.5.1 (Content-Disposition)` says that a parameter value can be a quoted string or a token. The section `2.2 (Basic Rules)` clearly says that a token is not a quoted string.
Now the parsing of the "name" and "filename" parameter values support only quoted string, and modern client-side frameworks tend to omit the quotes when not necessary, though still respecting the standard.
Moreover, the "name" parameter value can be empty, because the specification says the quoted string can be empty. So I replaced the + in the regular expression by a * symbol. The "filename" regular expression is already correct in term of character count matching.
Note that the new regular expressions should keep the correct amount of capturing groups, matching either one or the other.
I …
=> Improvement on Content-Disposition parsing

Readme.md, lib/incoming_form.js
I have seen this DeprecationWarning in the shell:
```
(node:19532) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```
This should fix this issue.
Thank you,
Christian
=> Fix DeprecationWarning's about os.tmpDir()

test/legacy/integration/test-multipart-parser.js, test/legacy/simple/test-multipart-parser.js
Node 7 throws on 
> Buffer.write(string, encoding, offset[, length]) is no longer supported
the order of arguments has changed.
=> Update buffer.write order of arguments

lib/file.js
This adds compatibility with [mock-fs](https://github.com/tschaub/mock-fs), which overrides these methods and expects modules to access them thereafter. This is merely a suggestion, as I don't know if you support making changes in order to support such things. However, I find the mock-fs module to be incredibly useful and would love to have it supported.
=> Access WriteStream of fs during runtime instead of include time

lib/file.js
When fileMaxSize reached _error() calls _writeStream.destroy() which turns into unhandled exception.
=> Fix using closed _writeStream when error is occurred (#357)

lib/incoming_form.js
while req emit the aborted event,OctetStream will not handle the tmp opened upload file release,this will cause file handle leak while long time run.
=> Fix OctetStreamtmp upload file cleanup while req aborted

CODE_OF_CONDUCT.md
Because. Why not. And because many people look for this in any community they participate.
=> chore: add Code of Conduct v1.4 file

lib/incoming_form.js
fix: the following request will cause uncatched error when parsed by formidable.
```
const fs = require('fs');
const path = require('path');
const request = require('request');
const multipartData = [
{name: 'my_field', body: 'my_value'},
{name: 'my_number', body: 1000},
{name: 'my_buffer', body: Buffer.from([1, 2, 3])},
{name: 'my_file', body: fs.createReadStream(path.resolve(__dirname, 'multipart.js'))},
// {name: 'remote_file', body: request(url + '/file')}
];
var reqOptions = {
url,
multipart: multipartData
}
request.post(reqOptions, function (err, res, body) {
console.log(body);
})
```
=> throw error during data parsing

lib/incoming_form.js
- This PR makes it available to send requests like the following:
`curl 'http://host/upload/with/params' -F 'topic=chat10' -F 'members[]=member_one@host.com' -F 'members[]=member_two@host.com' -F 'userfile=@./gplus.png'`
- Also it allows to distinguish the parameter type, whether it should be an array or not. It's important when the endpoint excpects the incoming parameters to be exactly of a certain type.
- Fixes the issue #138
=> Array parameters support

example/json.js, example/multipartParser.js, example/multiple.js, example/post.js, example/upload.js, test/legacy/simple/test-incoming-form.js, test/unit/test-incoming-form.js
fixes https://github.com/node-formidable/node-formidable/issues/518
=> Improve examples and tests

CHANGELOG.md, README.md, lib/index.js
- add `exports.default`
- update readme examples to **NOT** include `.IncomingForm` - it's unnecessary.
I don't want to promote using IncomingForm. It's still there for backward compat, but... never use it more.
=> feat: don't promote IncomingForm; support `exports.default` (esm)

examples/with-koa2.js, src/Formidable.js
- Make introduced `options.filename` from #591 work when `options.keepExtensions: true`.
- make `keepExtensions` work properly when multiple file extensions, like `.tar.gz`
=> fix: make opts.filename from #591 work with opts.keepExtensions

src/parsers/Multipart.js
Wrong arguments passed to the functions setMark/clearMarkSymbol inside the _transform method of the class MultipartParser
=> fix: multipart parser issue

CHANGELOG.md, src/Formidable.js
fixes #623
Somewhere in the commits of v2, we (probably me) introduced a bug that to now was causing text fields (and probably files named) in Cyrillic to be visual garbage.
Also, this check doesn't make much sense anyway. Because the `transferEncoding` most of the time is `'binary'` (one reason is that we set it to be default in `src/plugins/multipart` where we initiate the `part` stream), so the default `utf-8` encoding is never able to happen, even if set to different by the user thru the options.
=> fix: а regression in v2, causing cyrillic to fail

src/Formidable.js, src/plugins/multipart.js
Consider this PR for #623-like problems, instead of #624. 
here we use the same option found in DEFAULT_OPTIONS as everywhere else, instead of using binary which was passed through previously
=> revert #624, alternative fix for encoding/decoding

README.md, src/Formidable.js, test/unit/formidable.test.js
This PR introduces changes to support min file size and allow empty file options, therefore, closes #475. I tried to add some integration test for both options, but I have no success, I tried to follow the example of `test-fixtures.js` file, can you help me with this?
=> feat: add min size and empty file validation options

README.md, examples/log-file-content-to-console.js, examples/not-store-files.js, examples/store-files-on-s3.js, src/Formidable.js, src/PersistentFile.js, src/VolatileFile.js, src/index.js, src/plugins/octetstream.js, test/integration/test-file-write-stream-handler-option.js, test/integration/test-store-files-option.js, test/unit/persistent-file.test.js, test/unit/volatile-file.test.js
This PR introduces changes to support stores in the host machine files uploaded. The new option `storeFiles` with default value as `true` determines it, if `true` the files are parsed and stored, if `false` the files are only parsed. Closes #609.
- I tried to maintain this retro compatible and not introduce any breaking change.
- I thought to have a class for the base file to avoid duplication of code between `VolatileFile` and `PersistentFile`, but in the end, I thought it was not worthy. Let me know what you think about it.
- I focused more on integration tests for this PR because I think it maps better for this type of change, but let me know if I need to add more unit tests.
=> feat: add option to store files

CHANGELOG.md, README.md, examples/log-file-content-to-console.js, examples/store-files-on-s3.js, examples/with-http.js, package.json, src/Formidable.js, src/FormidableError.js, src/PersistentFile.js, src/VolatileFile.js, src/parsers/Multipart.js, src/parsers/StreamingQuerystring.js, src/plugins/multipart.js, src/plugins/octetstream.js, test/fixture/js/encoding.js, test/fixture/js/no-filename.js, test/fixture/js/preamble.js, test/fixture/js/special-chars-in-filename.js, test/fixture/js/workarounds.js, test/integration/file-write-stream-handler-option.test.js, test/integration/fixtures.test.js, test/integration/octet-stream.test.js, test/integration/store-files-option.test.js, test/standalone/content-transfer-encoding.test.js, test/unit/formidable.test.js, test/unit/persistent-file.test.js, test/unit/querystring-parser.test.js, test/unit/volatile-file.test.js
@tunnckoCore  Changed a bit how filename works (read the commit messages to get an overview)
fixes https://github.com/node-formidable/formidable/issues/672, https://github.com/node-formidable/formidable/issues/671, https://github.com/node-formidable/formidable/issues/389, https://github.com/node-formidable/formidable/issues/596, https://github.com/node-formidable/formidable/issues/465, https://github.com/node-formidable/formidable/pull/358
=> Safe default filename

CHANGELOG.md, examples/with-http.js, package.json, src/Formidable.js, src/parsers/Querystring.js, test/integration/file-write-stream-handler-option.test.js, test/integration/octet-stream.test.js, test/integration/store-files-option.test.js, test/standalone/issue-46.test.js, test/unit/formidable.test.js, yarn.lock
remove multiples
remove unused qs and querystring dependency
files and fields are always arrays to avoid type errors
use modern URLSearchParams https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams internally
=> Url search params and remove multiple

README.md
I have fixed the missing "=" in the options.filter.
**_Before_**
```js
const options {
filter: function ({name, originalFilename, mimetype}) {
// keep only images
return mimetype && mimetype.includes("image");
}
};
```
**_After_**
```js
const options = {
filter: function ({name, originalFilename, mimetype}) {
// keep only images
return mimetype && mimetype.includes("image");
}
};
```
=> Fixed the missing "=" in options.filter

CHANGELOG.md, package.json, src/Formidable.js, src/parsers/JSON.js, src/plugins/json.js
fixes https://github.com/node-formidable/formidable/issues/760
@Rush have a try
=> Handle top level json array

CHANGELOG.md, package.json, src/Formidable.js, src/FormidableError.js
=> fix: add missing error

src/PersistentFile.js, test/unit/persistent-file.test.js
Calling `toString()` on a `PersistentFile` was throwing:
```
Uncaught Rejection stack=TypeError: Cannot read property 'newFilename' of undefined
at PersistentFile.toString (formidable/src/PersistentFile.js:50:42)
```
It seems like `._file` wasn't set anywhere, and `toJSON` was using these directly anyway.
=> fix: PersistentFile.toString() doesn't throw

examples/multipart-parser.js, package.json, yarn.lock
formdata-polyfill is used by node-fetch as a way to serialize FormData to multipart payloads and it follows the spec to 100% and runs all test agains WPT. (the same serializer is also used by deno and undici) 
I thought you would be interested in using it (as discussed earlier)
maybe also for your test cases
---
so i updated multipart-parser.js in the example dir to construct a multipart payload (with files) with FormData instead of hand crafting a payload
=> Example of using FormData

package.json, test/standalone/issue-46.test.js, yarn.lock
request have been deprecated for a long time...
I took one body/header example out and using it as a static fixture example instead
Allows to remove request and many sub modules
=> refactor: Remove depr. request

.github/workflows/codeql-analysis.yml
LGTM bot is removed, parent company was bought by GitHub and they integrated its CodeQL product.
So..
=> chore(security): meta, add CodeQL action

src/Formidable.js, test/standalone/end-event-emitted-twice.test.js, test/standalone/keep-alive-error.test.js
closes to https://github.com/node-formidable/formidable/issues/810
=> fix: IncomingForm end event emitted twice

examples/with-http.js, package.json, src/Formidable.js, src/PersistentFile.js, test/unit/formidable.test.js
fixes https://github.com/node-formidable/formidable/issues/856
=> Improve keep extension

CHANGELOG.md, package.json, src/parsers/Multipart.js, test-node/standalone/createDirsFromUploads.test.js, test-node/standalone/multipart_parser.test.js
fixes https://github.com/node-formidable/formidable/issues/878
@stevenwdv @phpbg @hannesfant  @machineghost @lmammino please  review
=> fix: flush or fail always (don't hang)

CHANGELOG.md, package.json, src/Formidable.js, yarn.lock
Fixes https://github.com/node-formidable/formidable/issues/981
Supersedes https://github.com/node-formidable/formidable/pull/978
=> fix: update hexoid to v2

README.md, package.json, src/Formidable.js, test/integration/fixtures.test.js, test/standalone/connection-aborted.test.js, test/standalone/keep-alive-error.test.js, yarn.lock
we need to switch hexoid, because private vulnerability reports.
I already published a new patch for the v3, now for v2.
I also tried updating and fixing the tests.. no chance, let it fail. There are no breaking changes, the cuid2 is also 25 characters length, nothing else important is changed.
=> fix: switch hexoid to cuid2; try fixing tests - fail
