Readme.md

fixed incorrect documentation header/paragraph

---

lib/incoming_form.js
lib/json_parser.js

Now the JSON Parser emit an error event to the IncomingForm if a receive a malformed JSON request.
This way I can catch the error from my framework.

JSON Parser empty catch

---

lib/incoming_form.js

Use built-in toString to convert buffer to hex

---

package.json

npm is looking to include licenses in the top 1000 depended-upon projects! :) 
http://npm1k.org/

Include MIT license

---

Readme.md

Adding documentation for `maxFileSize` option

Documenting maxFileSize option

---

LICENSE

also added ", contributors" next to the @felixge. Let me know if something is not okey.

more standard formatting for the MIT license

---

.travis.yml
Readme.md
package.json

see https://github.com/node-formidable/node-formidable/issues/514

Support only node lts and latest

---

CHANGELOG.md
lib/incoming_form.js

/cc @charmander that should be better, yup.

use hasOwnProperty in check against files/fields

---

README.md

Because why not.
I just chose some random one, it kind of saying to me that the pieces are files/fields.
I don't really like green that much, but I'm okay with it.
I'll update the docs too in day or two.

Update and rename readme, add logo

---

lib/file.js

Nothing incredibly advanced, but might be useful for other people as it was for me.

Added a toString function that returns name and path of the file

---

lib/default_options.js
lib/file.js
lib/incoming_form.js
lib/multipart_parser.js

prefer template literals
avoid self = this

Code quality

---

test/legacy/simple/test-incoming-form.js

lets see if this fixes the things. Otherwise we'll just remove this test for now.

fix: attempt to fix the failing legacy test

---

.github/FUNDING.yml

part of #569 (joining to the Tidelift network)

feat: add Tidelift to GitHub FUNDING way

---

README.md

just found out about his post, so decided to link them here as well.

adding credits to more folks

---

src/Formidable.js
test/fixture/http/special-chars-in-filename/line-separator.http
test/fixture/js/special-chars-in-filename.js

Fixes https://github.com/node-formidable/formidable/issues/664

Handle u2028 in filename

---

src/Formidable.js
test/integration/test-json.js

Fixes https://github.com/node-formidable/formidable/issues/676

Fix multiple json

---

.github/workflows/nodejs.yml

Node 16 is soon to be released
Also https://github.com/nodejs/node/issues/31951

chore: up node version

---

CHANGELOG.md
README.md
package.json
src/helpers/firstValues.js
src/helpers/readBooleans.js
src/plugins/json.js
src/plugins/multipart.js
src/plugins/octetstream.js
src/plugins/querystring.js

Some helpers I successfully used in the past 9 months, that I genuinely think can be helpful to anyone using formidable to handle html forms

feat: add firstValues, readBooleans helpers

---

src/PersistentFile.js

fixes https://github.com/node-formidable/formidable/issues/797
@xHyroM please try this branch

fix: do not let empty file on error

---

.github/.kodiak.toml

Service for update & (auto)merging PRs
More on https://kodiakhq.com/

chore: add KodiakHQ service

---

.github/.kodiak.toml

chore: fix kodiak config

---

.github/dependabot.yml

Some stuff and to remove the annoying addition of `dependencies` label.

chore: add Dependabot settings

---

.github/dependabot.yml

chore(dependabot): do not add reviewers to dep update prs

---

README_pt_BR.md

The goal is to expand the community by facilitating understanding for Brazilian developers. I checked to ensure the minimum of translation errors that could cause problems.

Translation of README.md into Brazilian Portuguese.

---

CHANGELOG.md
README.md
package.json
tool/rollup.config.js
yarn.lock

@phpbg @hannesfant please review

Dual export
